// <auto-generated />
namespace Events4All.DB.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class add_attendee_cap : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_attendee_cap));
        
        string IMigrationMetadata.Id
        {
            get { return "201906051857520_add_attendee_cap"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
